word_list = [
    "Tedavi",
    "Yürümek",
    "Yeterli",
    "Alışveriş",
    "Hayal",
    "Ruh",
    "Düşünülmek",
    "Paylaşmak",
    "Sıkıntı",
    "Gaz",
    "Bilinç",
    "Herkes",
    "Fotoğraf",
    "sıcaklaştırma",
    "masumluk",
    "kimlik belgesi",
    "kokoreççi",
    "rulet",
    "Çeşme",
    "Bahçe",
    "bayramlaşma",
    "zalim",
    "jelatinleme",
    "badem",
    "kutuplaşmak",
    "kostüm",
    "mutluluk",
    "soğan",
    "Fransızca",
    "beyinsiz",
    "ademimerkeziyet",
    "losyon",
    "kene",
    "fizyoterapist",
    "sindirilme",
    "soykırım",
    "türbülans",
    "mahremiyet",
    "uygarlık",
    "turizm",
    "parmak izi",
    "anarşik",
    "kataloglamak",
    "muhafazakârlık",
    "mayın tarlası",
    "ihtiyatsızlık",
    "soda",
    "maden suyu",
    "Hatay",
    "haziran"
]